// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgw3mUOcIfZgrJAwMcaRptX5_kK89Bsaw',
    appId: '1:524258331861:web:a6c3a9a77472b50e8f665c',
    messagingSenderId: '524258331861',
    projectId: 'facialrecognition-1c5d1',
    authDomain: 'facialrecognition-1c5d1.firebaseapp.com',
    storageBucket: 'facialrecognition-1c5d1.firebasestorage.app',
    measurementId: 'G-73EEJ21X2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4nM92XvvP-Tu2V-7DmrGnjRiIxccdb1g',
    appId: '1:524258331861:android:bfa0adbfe69daab58f665c',
    messagingSenderId: '524258331861',
    projectId: 'facialrecognition-1c5d1',
    storageBucket: 'facialrecognition-1c5d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpd5LdQ9Gr4pbfP4hcTiWzYKM1-q25Ko',
    appId: '1:524258331861:ios:61763ccc4f0bdbfb8f665c',
    messagingSenderId: '524258331861',
    projectId: 'facialrecognition-1c5d1',
    storageBucket: 'facialrecognition-1c5d1.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpd5LdQ9Gr4pbfP4hcTiWzYKM1-q25Ko',
    appId: '1:524258331861:ios:61763ccc4f0bdbfb8f665c',
    messagingSenderId: '524258331861',
    projectId: 'facialrecognition-1c5d1',
    storageBucket: 'facialrecognition-1c5d1.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgw3mUOcIfZgrJAwMcaRptX5_kK89Bsaw',
    appId: '1:524258331861:web:ff3d2405b04d3de78f665c',
    messagingSenderId: '524258331861',
    projectId: 'facialrecognition-1c5d1',
    authDomain: 'facialrecognition-1c5d1.firebaseapp.com',
    storageBucket: 'facialrecognition-1c5d1.firebasestorage.app',
    measurementId: 'G-J6KKJJ18TB',
  );

}